#! /bin/bash

if [[ -z "$1" ]]; then
  echo >&2 "No subcommand provided."
  exit 1
fi

psql_server_version() {
  db="${PGDATABASE}"
  [[ -z "${db}" ]] && db=postgres
  psql --no-psqlrc --quiet --tuples-only --csv --dbname "${db}" --command 'show server_version;'
}

install_pgtap() {
  psql --no-psqlrc --quiet --dbname "${PGDATABASE}" \
    -f "/opt/pgtap/${version}/pgtap.sql" >/dev/null 2>&1
}

uninstall_pgtap() {
  psql --no-psqlrc --quiet --dbname "${PGDATABASE}" \
    -f "/opt/pgtap/${version}/uninstall_pgtap.sql" >/dev/null 2>&1
  psql --no-psqlrc --quiet --dbname "${PGDATABASE}" \
    --command "DROP FUNCTION IF EXISTS col_is_null (NAME, NAME, TEXT);" \
    --command "DROP FUNCTION IF EXISTS col_is_null (NAME, NAME, NAME, TEXT);" \
    --command "DROP FUNCTION IF EXISTS col_not_null (NAME, NAME, TEXT);" \
    --command "DROP FUNCTION IF EXISTS col_not_null (NAME, NAME, NAME, TEXT);" \
    --command "DROP FUNCTION IF EXISTS finish (BOOLEAN);" \
    --command "DROP FUNCTION IF EXISTS _finish (INTEGER, INTEGER, INTEGER, BOOLEAN);" \
    >/dev/null 2>&1
}

cd /repo || {
  echo >&2 "Error changing to /repo"
  exit 1
}

eol() {
  cat >&2 <<EOL
PostgreSQL $1 has reached end of life and support as of $2. Support is provided
on a best-effort basis.
EOL
}

beta() {
  cat >&2 <<BETA
PostgreSQL $1 is not yet released. Support is provided on a best-effort basis.
BETA
}

version=$(psql_server_version | tr -d ' \t\n\v\r')

case "${version}" in
9.6*)
  eol 9.6 2021-11-11
  version=9.6
  ;;
10*)
  eol 10 2022-11-10
  version=10
  ;;
11*)
  eol 11 2023-11-06
  version=11
  ;;
12*) version=12 ;;
13*) version=13 ;;
14*) version=14 ;;
15*) version=15 ;;
16*) version=16 ;;
17*) version=17 ;;
*)
  echo >&2 "Unknown or unsupported PostgreSQL version '${version}'."
  exit 1
  ;;
esac

case "$1" in
install) install_pgtap ;;
uninstall) uninstall_pgtap ;;
test)
  shift
  trap uninstall_pgtap EXIT
  install_pgtap
  pg_prove "$@"
  ;;
*)
  echo >&2 "Unknown command '$1'."
  exit 1
  ;;
esac
