#! /bin/bash

declare pgtap_version pgtap_hashref
pgtap_version="$(jq -r .pgtap.version /home/sqitch/package-versions.json)"
pgtap_hashref="$(jq -r .pgtap.hashref /home/sqitch/package-versions.json)"

[[ -n "${pgtap_hashref}" ]] && pgtap_version="${pgtap_version} (${pgtap_hashref})"

cat <<EOS
[gchr.io/]kineticcafe/sqitch-pgtap:$(cat /home/sqitch/VERSION)

  $(sqitch --version)
  pgtap ${pgtap_version}
  $(pg_prove --version)
EOS
