name: Build Test Image

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2.5.0

      - id: package-versions
        run: echo "data=$(cat package-versions.json)" >> $GITHUB_OUTPUT

      - id: docker_build
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          push: false
          load: true
          tags: kineticcafe/sqitch-pgtap:test
          build-args: |
            PG_PROVE_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pg_prove.version }}
            PGTAP_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pgtap.version }}
            SQITCH_VERSION=${{ fromJSON(steps.package-versions.outputs.data).sqitch.version }}

      - run: ./run version
        env:
          IMAGE: kineticcafe/sqitch-pgtap:test
