name: Build Test Image

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3.3.0

      - id: package-versions
        run: echo "data=$(cat package-versions.json)" >> $GITHUB_OUTPUT

      - id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: false
          load: true
          tags: kineticcafe/sqitch-pgtap:test
          build-args: |
            ALPINE_VERSION=${{ fromJSON(steps.package-versions.outputs.data).alpine.version }}
            PGTAP_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pgtap.version }}
            PG_PROVE_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pg_prove.version }}
            SQITCH_VERSION=${{ fromJSON(steps.package-versions.outputs.data).sqitch.version }}
            __DOCKERFILE_VERSION__=${{ fromJSON(steps.package-versions.outputs.data).VERSION }}
            __DOCKERFILE_DATE__=${{ fromJSON(steps.package-versions.outputs.data).DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: ./kineticcafe-sqitch-pgtap version
        env:
          IMAGE: kineticcafe/sqitch-pgtap:test
