name: Create Release and Push to Container Registries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true

jobs:
  make-release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
      - uses: ghalactic/github-release-from-tag@v5
        with:
          summaryEnabled: false
  publish-image:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            kineticcafe/sqitch-pgtap
            ghcr.io/kineticcafe/sqitch-pgtap
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - uses: docker/setup-qemu-action@v2.2.0
      - uses: docker/setup-buildx-action@v2.10.0

      - id: package-versions
        run: echo "data=$(cat package-versions.json)" >> $GITHUB_OUTPUT

      - id: docker_build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ALPINE_VERSION=${{ fromJSON(steps.package-versions.outputs.data).alpine.version }}
            PGTAP_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pgtap.version }}
            PG_PROVE_VERSION=${{ fromJSON(steps.package-versions.outputs.data).pg_prove.version }}
            SQITCH_VERSION=${{ fromJSON(steps.package-versions.outputs.data).sqitch.version }}
            __DOCKERFILE_VERSION__=${{ fromJSON(steps.package-versions.outputs.data).version }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: peter-evans/dockerhub-description@v3.4.2
        with:
          repository: kineticcafe/sqitch-pgtap
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
