name: Publish release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true

jobs:
  make-release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
      - uses: eloquent/github-release-action@v3
        with:
          summaryEnabled: false
  publish-image:
    uses: ./.github/workflows/build-and-push.yml
